version: '3'

services:
  docs:
    image: core_local_docs
    container_name: core_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./core:/app/core:z
    ports:
      - '9000:9000'
    command: /start-docs
