# Generated by Django 4.2.11 on 2024-08-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
