# Generated by Django 4.2.11 on 2024-08-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_contato_user_endereco_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InquilinoProfile',
            new_name='AgenteImobiliario',
        ),
        migrations.RenameModel(
            old_name='AgenteImobiliarioProfile',
            new_name='Inquilino',
        ),
        migrations.RenameModel(
            old_name='ClienteProfile',
            new_name='Proprietario',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('agente', 'Agente Imobiliário'), ('inquilino', 'Inquilino')], default='proprietario', max_length=20),
        ),
    ]
