# Generated by Django 4.2.11 on 2024-08-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_inquilinoprofile_agenteimobiliario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='tipo',
        ),
    ]
