# Generated by Django 4.2.11 on 2024-08-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_proprietario_preferencias_de_busca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contato',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
