# Generated by Django 4.2.11 on 2024-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type_userprofile_clienteprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente Imobiliário'), ('inquilino', 'Inquilino')], default='cliente', max_length=20),
        ),
        migrations.CreateModel(
            name='InquilinoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
