# Generated by Django 4.2.11 on 2024-10-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_agenteimobiliario_id_remove_inquilino_id_and_more'),
        ('propriedade', '0002_remove_imovel_foto_foto_imovel_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='users.proprietario'),
        ),
    ]
