# Generated by Django 4.2.11 on 2024-10-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade', '0003_alter_imovel_proprietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='tipodeimovel',
            options={'verbose_name_plural': 'Tipos de Imóveis'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='uf',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('estado', 'nome')},
        ),
    ]
