# Generated by Django 4.2.11 on 2024-10-16 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade', '0004_alter_cidade_options_alter_estado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
